### ISSUE TITLE
[2.X] Incorrect explosion behaviour with waterlogged blocks.

### ISSUE THREAD

**Issue by joserobjr** [GameModsBR/PowerNukkit#192]
Comparison on the links bellow (provided by @Gabriel8579). This issue will treat the 2.X behavior and #193 the 1.X version.

**Comment by Gabriel8579** [comment]
https://youtu.be/efLHclbVvV4 Comparing vanilla with 1.1.x (master branch)

**Comment by Gabriel8579** [comment]
https://youtu.be/MnQWCA_cFnk 2.0 (GameModsBr/v2.0/block/barrier/waterlogging branch)

Note: The first right-click with a water bucket on a fence doesn't work, the second right-click works but return the following error at the console:

``` java
14:33:22 [ERROR] Error whilst ticking server
java.lang.NullPointerException: null
	at cn.nukkit.item.ItemBucket.onActivate(ItemBucket.java:158) ~[classes/:?]
	at cn.nukkit.level.Level.useItemOn(Level.java:1838) ~[classes/:?]
	at cn.nukkit.level.Level.useItemOn(Level.java:1800) ~[classes/:?]
	at cn.nukkit.player.Player.onDataPacket(Player.java:2917) ~[classes/:?]
	at cn.nukkit.player.Player.checkNetwork(Player.java:1698) ~[classes/:?]
	at cn.nukkit.Server.tick(Server.java:969) ~[classes/:?]
	at cn.nukkit.Server.tickProcessor(Server.java:789) [classes/:?]
	at cn.nukkit.Server.start(Server.java:757) [classes/:?]
	at cn.nukkit.Server.boot(Server.java:593) [classes/:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:144) [classes/:?]

**Comment by joserobjr** [comment]
Thank you! I'm going to try to fix that tonight.
