### ISSUE TITLE
pls help 

### ISSUE THREAD

**Issue by zombihunterbonn** [GameModsBR/PowerNukkit#322]
# 💬 Let's talk

pls i need help

### 📋 Debug information

* PowerNukkit version: ✍
* Debug link: ✍

### 💬 Anything else we should know?

22:01:54 [ERROR] Throwing
java.lang.NoSuchMethodException: cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.<init>(cn.nukkit.network.SourceInterface, java.lang.Long, java.net.InetSocketAddress)
        at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_231]
        at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_231]
        at cn.nukkit.network.RakNetInterface.onSessionCreation(RakNetInterface.java:209) [nukkit-1.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetServer.onOpenConnectionRequest1(RakNetServer.java:171) [nukkit-1.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetServer.access$300(RakNetServer.java:31) [nukkit-1.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:280) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel.read(EpollDatagramChannel.java:688) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel.access$100(EpollDatagramChannel.java:57) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:507) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:502) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [nukkit-1.0-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]

**Comment by joserobjr** [comment]
Duplicated of #323
