### ISSUE TITLE
Incompatibility with Creeperface01's GAC

### ISSUE THREAD

**Issue by zombihunterbonn** [GameModsBR/PowerNukkit#323]
# 💬 Let's talk

pls help  me

### 📋 Debug information

* PowerNukkit version: 1.3.0.0-PN
* YouTrack: [PN-123](https://youtrack.gamemods.com.br/issue/PN-123)
* Debug link: https://hastebin.com/ofotohayah

### 💬 Anything else we should know?

```java
22:01:54 [ERROR] Throwing
java.lang.NoSuchMethodException: cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.<init>(cn.nukkit.network.SourceInterface, java.lang.Long, java.net.InetSocketAddress)
        at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_231]
        at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_231]
        at cn.nukkit.network.RakNetInterface.onSessionCreation(RakNetInterface.java:209) [nukkit-1.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetServer.onOpenConnectionRequest1(RakNetServer.java:171) [nukkit-1.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetServer.access$300(RakNetServer.java:31) [nukkit-1.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:280) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel.read(EpollDatagramChannel.java:688) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel.access$100(EpollDatagramChannel.java:57) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:507) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:502) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [nukkit-1.0-SNAPSHOT.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [nukkit-1.0-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
```

i onley edit the jar name for my start.sh

**Comment by joserobjr** [comment]
Is it happening at a startup? Can you send the link that is generated by `/debugpaste`, it will create a link sharing the plugin list, recent log, a few Nukkit configurations, and version details. The link usually expires automatically after some days (30 or 60 days, not sure)

**Comment by joserobjr** [comment]
Nevermore, I already found an incompatible class change:
https://github.com/Creeperface01/GAC/blob/master/src/main/java/cz/creeperface/nukkit/gac/player/NukkitCheatPlayer.kt#L13
https://github.com/GameModsBR/PowerNukkit/blob/2d414f23349f751992ada69dcb7fee7117064dda/src/main/java/cn/nukkit/Player.java#L611

**Comment by zombihunterbonn** [comment]
Yes here

https://hastebin.com/ofotohayah

joserobjr <notifications@github.com> schrieb am Mi., 1. Juli 2020, 22:24:

**Comment by zombihunterbonn** [comment]
Oh ok you now whats the problem

Mario Heberling <mario00220088@gmail.com> schrieb am Mi., 1. Juli 2020,
22:26:

**Comment by zombihunterbonn** [comment]
What can i do ?

Mario Heberling <mario00220088@gmail.com> schrieb am Mi., 1. Juli 2020,
22:30:

**Comment by joserobjr** [comment]
You need to temporarily remove GAC until this issue gets resolved. It's planned for 1.4.0.0 but if the fix is simple it can be released earlier.

**Comment by zombihunterbonn** [comment]
Thx Good job powernukkit best!

joserobjr <notifications@github.com> schrieb am Mi., 1. Juli 2020, 22:44:

**Comment by zombihunterbonn** [comment]
Mob plugin is fix now?

Mario Heberling <mario00220088@gmail.com> schrieb am Mi., 1. Juli 2020,
22:45:

**Comment by joserobjr** [comment]
The mob plugin needs to be retested with this build (or higher) https://github.com/GameModsBR/PowerNukkit/actions/runs/154206954

It could be being affected by a potential memory leak in the RakNet library

**Comment by joserobjr** [comment]
Can you verify if this build fixes the issue?
https://github.com/GameModsBR/PowerNukkit/actions/runs/154621557

**Comment by MrRazamataz** [comment]
@joserobjr @zombihunterbonn CreeperFace offers a version that supports the newer raknet. 

https://mega.nz/file/pCwkDCwI#_CtyyIvfOWA6QBXolk9LMhSrU3FJu5FsBhZ9emLF4LA

**Comment by MrRazamataz** [comment]
> Can you verify if this build fixes the issue?
> https://github.com/GameModsBR/PowerNukkit/actions/runs/154621557

Does this mean I can use the normal version of GAC?

**Comment by joserobjr** [comment]
@MrRazamataz yes, I didn't notice the new-raknet version but apparently the only issue was the Player constructor. Synapse might also have some constructor compatibility issue but that would be an other topic.
https://github.com/Creeperface01/GAC/compare/new-raknet?expand=1

With this change both versions should work now, but the new-raknet version should be a little bit faster

**Comment by MrRazamataz** [comment]
Ok thanks.

**Comment by good777LUCKY** [comment]
@joserobjr I have another problem with GAC.
![Screenshot](https://user-images.githubusercontent.com/43497313/86331920-b6650480-bc84-11ea-872b-c11fbc06d8f8.jpg)

**Comment by good777LUCKY** [comment]
It is repeating and client will disconnect randomly

**Comment by tuilakhanh** [comment]
Should you use GAC new raknet version ? It work perfectly on my powernukkit server

**Comment by good777LUCKY** [comment]
Oh I don't use new raknet version, i will use it
